const codes = [
	{en: 'Tornado', pt: 'Tornado'},
	{en: 'Tropical storm', pt: 'Tempestade tropical'},
	{en: 'Hurricane', pt: 'Furacão'},
	{en: 'Severe thunderstorms', pt: 'Trovoadas severas'},
	{en: 'Thunderstorms', pt: 'Trovoadas'},
	{en: 'Mixed rain and snow', pt: 'Chuva e neve'},
	{en: 'Mixed rain and sleet', pt: 'Chuva e granizo'},
	{en: 'Mixed snow and sleet', pt: 'Neve e granizo'},
	{en: 'Freezing drizzle', pt: 'Chuviscos gelados'},
	{en: 'Drizzle', pt: 'Chuviscos'},
	{en: 'Freezing rain', pt: 'Chuva congelante'},
	{en: 'Showers', pt: 'Pancadas de chuva'},
	{en: 'Rain', pt: 'Chuva'},
	{en: 'Snow flurries', pt: 'Flocos de neve'},
	{en: 'Light snow showers', pt: 'Nevascas leves'},
	{en: 'Blowing snow', pt: 'Sopros de neve'},
	{en: 'Snow', pt: 'Neve'},
	{en: 'Hail', pt: 'Granizo'},
	{en: 'Sleet', pt: 'Chuva de granizo'},
	{en: 'Dust', pt: 'Poeira'},
	{en: 'Foggy', pt: 'Nebuloso'},
	{en: 'Haze', pt: 'Neblina'},
	{en: 'Smoky', pt: 'Neblina'},
	{en: 'Blustery', pt: 'Períodos de ventos'},
	{en: 'Windy', pt: 'Tempo ventoso'},
	{en: 'Cold', pt: 'Frio'},
	{en: 'Cloudy', pt: 'Nublado'},
	{en: 'Mostly cloudy (night)', pt: 'Predominantemente nublado'},
	{en: 'Mostly cloudy (day)', pt: 'Predominantemente nublado'},
	{en: 'Partly cloudy (night)', pt: 'Parcialmente nublado'},
	{en: 'Partly cloudy (day)', pt: 'Parcialmente nublado'},
	{en: 'Clear (night)', pt: 'Noite clara'},
	{en: 'Sunny', pt: 'Ensolarado'},
	{en: 'Fair (night)', pt: 'Céu limpo'},
	{en: 'Fair (day)', pt: 'Céu limpo'},
	{en: 'Mixed rain and hail', pt: 'Chuva e granizo'},
	{en: 'Hot', pt: 'Quente'},
	{en: 'Isolated thunderstorms', pt: 'Trovoadas esparsas'},
	{en: 'Scattered thunderstorms', pt: 'Trovoadas esparsas'},
	{en: 'Scattered showers (day)', pt: 'Chuvas dispersas'},
	{en: 'Heavy rain', pt: 'Chuva pesada'},
	{en: 'Scattered snow showers (day)', pt: 'Nevascas esparsas'},
	{en: 'Heavy snow', pt: 'Neve pesada'},
	{en: 'Blizzard', pt: 'Nevasca'},
	{en: 'Not available', pt: 'Indisponível'},
	{en: 'Scattered showers (night)', pt: 'Chuvas esparsas'},
	{en: 'Scattered snow showers (night)', pt: 'Nevascas esparsas'},
	{en: 'Scattered thundershowers', pt: 'Trovoadas esparsas'}
];

const weekDays = {
	'Sun': 'Dom',
	'Mon': 'Seg',
	'Tue': 'Ter',
	'Wed': 'Qua',
	'Thu': 'Qui',
	'Fri': 'Sex',
	'Sat': 'Sat',
};

export {codes, weekDays};